SWPROT-8953: Disable Werror on UnifySDK dep release
As explain in patch it is good to use Werror in devel or ci branch
not in releases (tags).

This change is not yet applied upstream,
to support more compilers, issue has been reported on OSX using

```
➜  ~ cc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
➜  ~ c++ --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I would be nice to fix this in the upstream too:

    .../unifysdk-src/components/uic_main/src/uic_init.c:77:21: \
    error: passing arguments to 'sl_log_read_config' \
    without a prototype is deprecated in all versions of C \
    and is not supported in C2x \
    [-Werror,-Wdeprecated-non-prototype]
    sl_log_read_config(NULL);

Origin: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/25
Signed-off-by: Philippe Coval <philippe.coval@silabs.com>