SWPROT-8953: Import UnifySDK ver_1.6.0 codebase for ZPC
This has been adjusted for zpc import:

- Hot fix adjust space changes to align to tag
- git-lfs: Remote LFS assets not used for zpc

The squashed commit (git clone --depth=1)
could not have been preserved because of failure to upload some object:

    remote: Resolving deltas: 100% (9897/9897), done.
    remote: fatal: did not receive expected object 8c3c67c057db0a6aa6ac986c38e9ec9fbdac707c
    error: remote unpack failed: index-pack failed

Origin: https://github.com/SiliconLabs/UnifySDK/releases/tag/ver_1.6.0
Fowarded: https://github.com/SiliconLabsSoftware/unify-z-wave/pull/1
Signed-off-by: Philippe Coval <philippe.coval@silabs.com>